### ISSUE TITLE
Angular Comments

### ISSUE THREAD

**Issue by Ari-Shatunovsky** [lanaleyla/CVAngularShop#1]
1. Using ngOnChanges in your case in not optimal way to display products. It is much better to handle that on category select via click event.
2. Use string templates instead of +
3. Use interfaces for your Products and Categories
4. Use for of loop to iterate over array
5. Use lower case for field names
6. Images are stretched.
7. Use single quotes instead of double.

**Comment by lanaleyla** [comment]
fixed it
